// <auto-generated />
using System;
using GrantPath.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrantPath.Data.Migrations
{
    [DbContext(typeof(GrantPathDbContext))]
    partial class GrantPathDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrantPath.Data.AbacPolicyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_json");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Effect")
                        .HasColumnType("integer")
                        .HasColumnName("effect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_abac_policies");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("ix_abac_policies_resource_type");

                    b.ToTable("abac_policies", (string)null);
                });

            modelBuilder.Entity("GrantPath.Data.AuthorizationDecisionRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("AttributeVerdict")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("attribute_verdict");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_id");

                    b.Property<string>("ReasonJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reason_json");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relation");

                    b.Property<bool>("RelationshipAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("relationship_allowed");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<bool>("WrittenSynchronously")
                        .HasColumnType("boolean")
                        .HasColumnName("written_synchronously");

                    b.HasKey("RequestId")
                        .HasName("pk_authz_decisions");

                    b.HasIndex("Resource", "DecidedAtUtc")
                        .HasDatabaseName("ix_authz_decisions_resource_decided_at_utc");

                    b.HasIndex("Subject", "DecidedAtUtc")
                        .HasDatabaseName("ix_authz_decisions_subject_decided_at_utc");

                    b.ToTable("authz_decisions", (string)null);
                });

            modelBuilder.Entity("GrantPath.Data.ChangelogCursor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ContinuationToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("continuation_token");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_changelog_cursor");

                    b.ToTable("changelog_cursor", (string)null);
                });

            modelBuilder.Entity("GrantPath.Data.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("folder_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_documents_folder_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("GrantPath.Data.DocumentPermissionCacheEntry", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("document_id");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<string>("Relation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("relation");

                    b.Property<DateTimeOffset>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at_utc");

                    b.HasKey("DocumentId", "Subject", "Relation")
                        .HasName("pk_document_permission_cache");

                    b.ToTable("document_permission_cache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
